### ISSUE TITLE
Champion Gallery

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/League_Collection_App#1]
# Userstory

## Value Proposition

**As a** USER
**I want to** see a list of all champions
**so that** see what kind of champion I already own

## Description

Render a list of all champions.
Clicking on the images will highlight them.
There is a counter on top to track the amount.
Later on when the calculation feature got added the top section will display the calculated prices.

## Acceptance Criteria

- [x] Champion names are displayed
- [x] Champion tile image are displayed
- [x] Clicking on the image will highlight them
- [ ] Counter is displayed on the top

## Tasks

- [x] Create a champion gallery page
- [x] Create a champion card component
- [x] Add a state to each card
- [ ] Add a champion counter component

## Complexity

(Size M)
