### ISSUE TITLE
Legal Pages

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/League_Collection_App#3]
# Legal Pages

## Value Proposition

**As a** Author
**I want to** have some legal pages
**so that** I don't have to worry about the legal stuff

## Description

Adding some legal pages.
- Imprint page
- Data Privacy page
- Riot's Legal Jibber Jabber

## Acceptance Criteria

- [x] Link to the pages are displayed in the footer
- [x] Every external link is marked

## Tasks

- [x] Create Imprint page
- [x] Create Data Privacy page
- [x] Create Link to Riot's legal dev site
- [x] Create Link to my Github

## Complexity

(Size M)
