### ISSUE TITLE
Bot Game Champion Collection

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/League_Collection_App#4]
# Protean Override Challenges

## Value Proposition

**As a** USER
**I want to** a track champion I already used in bot game
**so that** I don't have to always click inside the achievement pages after every game.

## Description

A page to track champion the user already used in a bot game for the bot game challenges.
Similar to the champion collection page

## Acceptance Criteria

- [x] Champion list is displayed
- [x] If the the champion is check marked the champion is de-saturated.

## Tasks

- [x] Create bot game collection page
- [x] Create a check mark to the champion list

## Complexity

(Sizes L)
